### ISSUE TITLE
Scripts to help setup a Developers PC into a Trainers PC

### ISSUE THREAD

**Issue by mblack88** [github/training-utils#17]
I recently went through GitHub's Certified Trainer sessions here at Ford.
One of the things that @brianamarie was rather **Harsh** on me about was my use of **alias'**.   :grin: 
Other items she mentioned as **Distractions** to students were **popup** messages and lots of bookmarks on your browsers toolbar.
In the Spirit of the training I came up with, rather quickly, a set of Windows :nauseated_face: batch files that help me setup my laptop to give training.
You can find them here: https://github.com/mblack88/training-scripts
@brianamarie thought they might make a decent contribution to your training utils, but I'm not sure how to bring in these Windows specific items into what you already have here.
I would like to start the discussion and see what all your thoughts are.

**Let the Fun Begin**

**Comment by brianamarie** [comment]
cc @github/services-training for insight on how to incorporate these ✨ Windows scripts into `training-utils` for future re-use 👀

**Comment by brianamarie** [comment]
PS @mblack88 You are awesome, thank you for a) having this great idea, b) making it real with the script, and c) investing into sharing it and reuse for others. ❤️ 

![](https://media.giphy.com/media/JQQwgVUMDIyAM/giphy.gif)

**Comment by crichID** [comment]
@mblack88 thank you for investing the effort in these scripts. I think they would make a :sparkles: addition to these resources. One option for incorporating these scripts into the repository would be to add them to a Windows folder. The repository generally uses a bootstrap script to create paths to the individual commands, but I know Ruby doesn't :heart: Windows (or maybe the other way around) so perhaps we would forego that level of convenience for now.

Of course, once you have added these, everyone will want similar scripts for Mac (ahem @stoe)

**Comment by mblack88** [comment]
@crichID Let me take a quick look at Ruby, need to **Learn** it.
I would like to make these a bit more generic, and maybe have a script that takes an input file for the things to terminate and then act appropriately for the **OS** it is running on.

**Comment by stoe** [comment]
> Of course, once you have added these, everyone will want similar scripts for Mac (ahem @stoe)

On Mac (and Linux, I guess) one can do this via [dotfiles](http://dotfiles.github.io/) and different branches.

I personally use a [dotfiles](https://github.com/stoe/dotfiles) approach.
- [master branch](https://github.com/stoe/dotfiles/tree/master) for every day work
- [training branch](https://github.com/stoe/dotfiles/tree/training) when I teach classes

The two different options allow me to change my terminal and text editor setup.

### Every Day
dark themes with smaller font size
![image](https://cloud.githubusercontent.com/assets/203805/25432920/c6b66ae2-2a86-11e7-9061-3de742c30508.png)
![image](https://cloud.githubusercontent.com/assets/203805/25432944/db35411e-2a86-11e7-93c4-1364910daa21.png)

### Training
light themes with large font size
![image](https://cloud.githubusercontent.com/assets/203805/25432969/f59ffaf8-2a86-11e7-9f7f-4f491dffcebd.png)
![image](https://cloud.githubusercontent.com/assets/203805/25433004/17b1b60e-2a87-11e7-9aaf-ce0b74e2bff9.png)
