### ISSUE TITLE
List other tools

### ISSUE THREAD

**Issue by afeld** [github/training-utils#2]
I remember seeing @matthewmccullough (?) use some other tools in a training, e.g. something to highlight the mouse pointer, etc. Mind adding those to the README? A couple examples:
- [Caffeine](https://itunes.apple.com/us/app/caffeine/id411246225)
- [Mouseposé](https://itunes.apple.com/app/mousepose/id405904955?mt=12)

**Comment by matthewmccullough** [comment]
Howdy @afeld! Nice to get to say hi to you on the interwebs.  I miss co-working with you from time to time.

Would you be able to PR those in?  Good ideas.

Others include:
- [ScreenFlow](http://www.telestream.net/screenflow/overview.htm) for recording screen casts
- Skitch classic for Mac OSX (hard DMG to find nowadays)
- [Quickres](http://www.quickresapp.com/)
- [Switch ResX](http://www.madrau.com/)
- [Shush](https://itunes.apple.com/us/app/shush-microphone-manager/id496437906?mt=12)

**Comment by matthewmccullough** [comment]
And [AirSketch](http://www.qrayon.com/home/airsketch/)

**Comment by afeld** [comment]
Just tried [keycastr](https://github.com/keycastr/keycastr) and it's pretty awesome.

**Comment by matthewmccullough** [comment]
@afeld :+1:.  Also, in a two-for-one type of effort, [Mouseposé](https://itunes.apple.com/app/mousepose/id405904955?mt=12) includes a key-display function.

**Comment by afeld** [comment]
Have any of you tried Camtasia? Curious about your opinion on it, relative to ScreenFlow.

**Comment by PeterBell** [comment]
@afeld generally Camtasia is usually described as the better option on a PC but the worse option on a Mac. I've seen pretty good consensus on this between @matthewmccullough and the training team, the author list for Pluralsight and elsewhere - at least last time I asked all of them.
