### ISSUE TITLE
Necessary modification to make **historytailbash** work

### ISSUE THREAD

**Issue by mblack88** [github/training-utils#20]
I found that my default **git bash** terminal on my windows PC did not work correctly with the **historytailbash** script.
It turns out that the **history** file was only written to when the terminal was closed and not after each command.
We found the following changes to the ~/.bashrc file allowed the history file to be updated after each command was typed, which allowed the **historytailbash** script to actually display correctly.

Changes needed to be added to the  ~/.bashrc
```
shopt -s histappend
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
```

I am not sure which documentation to add this information to.  My first thought is to the **historytailbash** script itself as comments in the header, but would like a discussion.

**Comment by mblack88** [comment]
@hollenberry @brianamarie @crichID 
Wanted to assign you guys to this, but I don't seem to have permission to add Assignee's.

**Comment by crichID** [comment]
> Wanted to assign you guys to this, but I don't seem to have permission to add Assignee's.

@mblack88 thank you for the ping and for making note of this update - do you want to open a PR so you can get the little green square :wink:?

**Comment by mblack88** [comment]
Based on the response it sounds like you agree where to put this information. I will create a PR later this morning.

Sent from my iPhone

On Sep 4, 2018, at 10:10 PM, Cynthia Rich <notifications@github.com<mailto:notifications@github.com>> wrote:


Wanted to assign you guys to this, but I don't seem to have permission to add Assignee's.

@mblack88<https://github.com/mblack88> thank you for the ping and for making note of this update - do you want to open a PR so you can get the little green square 😉?

**Comment by crichID** [comment]
> I am not sure which documentation to add this information to. My first thought is to the historytailbash script itself as comments in the header, but would like a discussion.

@mblack88 you caught me, my eyes stopped reading at the code block. Yes, I think comments in the header and/or adding this to the README of this repo would be ideal.
