### ISSUE TITLE
Update install script(s)

### ISSUE THREAD

**Issue by patrickmckenna** [github/training-utils#8]
@github/training-teachers We don't currently list the dependencies needed by some of these scripts, or have any scripts to install those deps. (I didn't even realize this until this morning, when I couldn't run [`add-collaborators`](https://github.com/github/training-utils/blob/c24d2334101f6600abb806dbdc671206261fb37e/add-collaborators) because I recently reinstalled OS X and didn't have [`octokit`](https://github.com/octokit/octokit.rb) installed.)

Question the first: should we add that? I vote yes.

Question two: should we just modify the [`Rakefile`](https://github.com/github/training-utils/blob/c24d2334101f6600abb806dbdc671206261fb37e/Rakefile), or should we follow the conventions of [Scripts to Rule Them All](https://github.com/github/scripts-to-rule-them-all)? (We'd omit the unneeded bits from the latter, of course, e.g. [`script/console`](https://github.com/github/scripts-to-rule-them-all/blob/master/script/console).) I vote for the second path, for consistency's sake, something that's especially important for new users and new hires.

Thoughts?

**Comment by brntbeer** [comment]
:+1: for adding that
:+1: for dependencies listed in scripts. especially making sure the folder is `/script`, and `./script/bootstrap` would bail if octokit wasn't setup, etc

**Comment by crichID** [comment]
@patrickmckenna - thank you so much for your :eyes: for these details. 

> Question the first: should we add that?

:+1: 

> should we follow the conventions of Scripts to Rule Them All?

I :+1: option B
